causal_gpt2:
  hf_model_name: openai-community/gpt2
  weights_model_name: gpt2  # Key in model_weights.yaml for downloading safetensors
  num_nodes: 3
  num_layers: 12
  max_new_tokens: 256
  
  # Active decoding strategy to use
  active_decoding_strategy: top_k
  
  # Decoding strategies with their hyperparameters
  decoding_strategies:
    greedy:
      temperature: 1.0
    
    sampling:
      temperature: 1.0
    
    top_p:
      temperature: 1.0
      p: 0.9
    
    top_k:
      temperature: 1.0
      k: 40