host_ip:
  mini1: "10.10.0.1"
  mini2: "10.10.0.1"
  mini3: "10.10.0.1"
  macbook: "10.10.0.1"
  pi5: "172.18.3.180"

port: 65432

# Worker update settings
worker_update_interval: 5  # How often workers pull latest weights (in steps)

# Randomness seed
seed: 42

# Cluster configuration
num_workers: 4
workers: [macbook, mini2, mini3, pi5]  # Worker hostnames
server: mini1  # Server hostname