host_ip:
  mini1: "10.10.0.1"
  mini2: "10.10.0.1"
  mini3: "10.10.0.1"
  # pi4: "192.168.51.4"
  # pi5: "192.168.50.2"
  # macbook: "172.18.3.80"
  # win: "10.10.0.1"

port: 65432


# Worker update settings
worker_update_interval: 10  # How often workers pull latest weights (in steps)

# Timeout for gradient collection
timeout: 0.1  # How long server waits for gradients (seconds)

# Randomness seed
seed: 42

# Cluster configuration
num_workers: 2
workers: [mini2, mini3]  # Worker hostnames
server: mini1  # Server hostname
