host_ip:
  mini1: "127.0.0.1"
  mini2: "127.0.0.1"
  mini3: "127.0.0.1"
  pi4: "127.0.0.1"
  macbook: "127.0.0.1"
  pi5: "127.0.0.1"
  win: "127.0.0.1"
  localhost: "127.0.0.1"

port: 65432


# Timeout for gradient collection
timeout: 0.1  # How long server waits for gradients (seconds)

# Randomness seed
seed: 42

# Cluster configuration
num_workers: 2
workers: [localhost, localhost]  # Worker hostnames (will run as separate processes)
server: localhost  # Server hostname

#Model parallelism specific configs
num_nodes: 3
num_layers: 6  # Number of transformer blocks (auto-detected from model, this is just for reference)
model_name: causal_gpt2 