host_ip:
  mini1: "10.10.0.1"
  mini2: "10.10.0.1"
  # mini3: "10.10.0.1"
  # macbook: "172.18.3.80"
  pi5: "192.168.50.1"

port: 65432

# Worker update settings
worker_update_interval: 50  # How often workers pull latest weights (in steps)

# Quantization settings
use_quantization: true  # Enable/disable weight quantization for communication

# Randomness seed
seed: 42

# Cluster configuration
num_workers: 2
workers: [mini2, pi5]  # Worker hostnames
server: mini1  # Server hostname