host_ip:
  mini1: "10.10.0.1"
  mini2: "10.10.0.2"
  mini3: "10.10.0.3"
  macbook: "10.10.0.4"
  # pi5: "172.18.3.80"

port: 65432

# Worker update settings
worker_update_interval: 5  # How often workers pull latest weights (in steps)

# Randomness seed
seed: 42

# Cluster configuration
num_workers: 3
workers: [mini2, mini3, macbook]  # Worker hostnames
server: mini1  # Server hostname