host_ip:
  mini1: "10.10.0.1"
  # mini2: "10.10.0.1"
  # mini3: "10.10.0.1"
  pi4: "10.10.0.1"
  # macbook: "172.18.3.80"
  pi5: "192.168.50.1"
  windows11: "192.168.52.2"

port: 65432

# Worker update settings
worker_update_interval: 10  # How often workers pull latest weights (in steps)

# Quantization settings
use_quantization: false  # Enable/disable weight quantization for communication

# Randomness seed
seed: 42

# Cluster configuration
num_workers: 3
workers: [windows11, pi4, pi5]  # Worker hostnames
server: mini1  # Server hostname