host_ip:
  mini1: "10.10.0.1"
  mini2: "10.10.0.1"
  mini3: "10.10.0.1"
  # pi5: "10.10.0.1"

port: 65432

# Worker update settings
worker_update_interval: 5  # How often workers pull latest weights (in steps)

# Randomness seed
seed: 42

# Cluster configuration
num_workers: 2
workers: [mini2, mini3]  # Worker hostnames
server: mini1  # Server hostname
