host_ip:
  mini1: "10.10.0.1"
  mini2: "10.10.0.1"
  mini3: "10.10.0.1"
  pi4: "10.10.0.1"
  macbook: "10.10.0.1"
  pi5: "192.168.50.1"
  win: "10.10.0.1"

port: 65432

# Worker update settings
worker_update_interval: 200  # How often workers pull latest weights (in steps)

# Quantization settings
use_quantization: false  # Enable/disable weight quantization for communication

track_gradients: true  # Whether server tracks gradient norms for each worker

polyark_average_update: 100  # How often to perform Polyark averaging (in steps)

# Randomness seed
seed: 42

control_message_queue_size: 100  # Size of the gradient queue for each worker
data_message_queue_size: 100  # Size of the data queue for each worker

# Cluster configuration
num_workers: 2
workers: [mini2, mini3]  # Worker hostnames
server: mini1  # Server hostname