host_ip:
  mini1: "10.10.0.1"
  mini2: "10.10.0.1"
  # mini3: "10.10.0.1"
  macbook: "172.18.3.80"
  # pi5: "192.168.50.1"

port: 65432

# Worker update settings
worker_update_interval: 20  # How often workers pull latest weights (in steps)

# Randomness seed
seed: 42

# Cluster configuration
num_workers: 2
workers: [macbook, mini2]  # Worker hostnames
server: mini1  # Server hostname