_wandb:
    value:
        cli_version: 0.23.1
        e:
            9s06kio4aw7a6oso652h28gcyr8x6kpj:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "3221225472"
                codePath: src/smolcluster/worker.py
                codePathLocal: worker.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "197279993856"
                email: rajceo2031@gmail.com
                executable: /Users/yuvrajsingh9886/Desktop/smolcluster/.venv/bin/python3
                git:
                    commit: ce1e74add5763665a3db50e3cba408117c23866c
                    remote: https://github.com/YuvrajSingh-mist/smolcluster.git
                host: Yuvrajs-MacBook-Air-6210.local
                memory:
                    total: "8589934592"
                os: macOS-26.2-arm64-arm-64bit-Mach-O
                program: /Users/yuvrajsingh9886/Desktop/smolcluster/src/smolcluster/./worker.py
                python: CPython 3.13.2
                root: /Users/yuvrajsingh9886/Desktop/smolcluster/src/smolcluster
                startedAt: "2026-01-02T20:33:40.031525Z"
                writerId: 9s06kio4aw7a6oso652h28gcyr8x6kpj
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.13.2
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 4
dataset:
    value:
        name: MNIST
eval_step:
    value: 50
learning_rate:
    value: 0.001
model:
    value:
        activation: relu
        hidden: 128
        input_dim: 784
        out: 10
        type: SimpleNN
num_epochs:
    value: 10
